AWSTemplateFormatVersion: '2010-09-09'
Description: POC of AWS-SDK Service Stack

Resources:
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'

  CloudFormationServiceMangedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed Policy to attach to CloudFormationServiceRole Role
      ManagedPolicyName: CloudFormationServiceMangedPolicyForCloudFormation
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:*'
              - 'iam:*'
              - 'cognito:*'
              - 'cognito-idp:*'
            Resource: '*'
      Roles:
        - !Ref CloudFormationServiceRole

Outputs:
  Version:
    Value: 1